=== Docker Build Log for b5e7a80691ed5e44e7fea1964bae18dc ===
Started at: Mi 29. Okt 19:31:26 CET 2025

[2025-10-29 19:31:26] START: Building image for b5e7a80691ed5e44e7fea1964bae18dc
#0 building with "default" instance using docker driver

#1 [internal] load build definition from Dockerfile
#1 transferring dockerfile: 187B done
#1 DONE 0.0s

#2 [internal] load metadata for docker.io/library/python:3.11
#2 DONE 0.0s

#3 [internal] load .dockerignore
#3 transferring context: 2B done
#3 DONE 0.0s

#4 [internal] load build context
#4 transferring context: 12.93kB 0.0s done
#4 DONE 0.0s

#5 [1/3] FROM docker.io/library/python:3.11
#5 CACHED

#6 [2/3] COPY hard-gists/b5e7a80691ed5e44e7fea1964bae18dc/snippet.py /snippet.py
#6 DONE 0.1s

#7 [3/3] RUN ["pip","install","idc"]
#7 1.967 Collecting idc
#7 2.007   Downloading idc-0.6.0.tar.gz (850 kB)
#7 2.089      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 850.4/850.4 kB 11.0 MB/s eta 0:00:00
#7 2.125   Preparing metadata (setup.py): started
#7 3.098   Preparing metadata (setup.py): finished with status 'done'
#7 3.131 Collecting pyOSC==0.3.5b-5294 (from idc)
#7 3.142   Downloading pyOSC-0.3.5b-5294.tar.gz (33 kB)
#7 3.159   Preparing metadata (setup.py): started
#7 3.249   Preparing metadata (setup.py): finished with status 'error'
#7 3.253   error: subprocess-exited-with-error
#7 3.253   
#7 3.253   × python setup.py egg_info did not run successfully.
#7 3.253   │ exit code: 1
#7 3.253   ╰─> [9 lines of output]
#7 3.253       Traceback (most recent call last):
#7 3.253         File "<string>", line 2, in <module>
#7 3.253         File "<pip-setuptools-caller>", line 34, in <module>
#7 3.253         File "/tmp/pip-install-9715lnqg/pyosc_f4877fb13c47438aacdd1efa202a2196/setup.py", line 5, in <module>
#7 3.253           import OSC
#7 3.253         File "/tmp/pip-install-9715lnqg/pyosc_f4877fb13c47438aacdd1efa202a2196/OSC.py", line 735
#7 3.253           binary = struct.pack('>ll', 0L, 1L)
#7 3.253                                       ^
#7 3.253       SyntaxError: invalid decimal literal
#7 3.253       [end of output]
#7 3.253   
#7 3.253   note: This error originates from a subprocess, and is likely not a problem with pip.
#7 3.254 error: metadata-generation-failed
#7 3.254 
#7 3.254 × Encountered error while generating package metadata.
#7 3.254 ╰─> See above for output.
#7 3.254 
#7 3.254 note: This is an issue with the package mentioned above, not pip.
#7 3.254 hint: See above for details.
#7 3.359 
#7 3.359 [notice] A new release of pip is available: 24.0 -> 25.3
#7 3.359 [notice] To update, run: pip install --upgrade pip
#7 ERROR: process "pip install idc" did not complete successfully: exit code: 1
------
 > [3/3] RUN ["pip","install","idc"]:
3.254 error: metadata-generation-failed
3.254 
3.254 × Encountered error while generating package metadata.
3.254 ╰─> See above for output.
3.254 
3.254 note: This is an issue with the package mentioned above, not pip.
3.254 hint: See above for details.
3.359 
3.359 [notice] A new release of pip is available: 24.0 -> 25.3
3.359 [notice] To update, run: pip install --upgrade pip
------
Dockerfile:3
--------------------
   1 |     FROM python:3.11
   2 |     COPY hard-gists/b5e7a80691ed5e44e7fea1964bae18dc/snippet.py /snippet.py
   3 | >>> RUN ["pip","install","idc"]
   4 |     CMD ["python3","/snippet.py"]
   5 |     
--------------------
ERROR: failed to build: failed to solve: process "pip install idc" did not complete successfully: exit code: 1

View build details: docker-desktop://dashboard/build/default/default/p8tqnw4fxkqtyrtxq59dved1b
[2025-10-29 19:31:30] ERROR: Build failed for b5e7a80691ed5e44e7fea1964bae18dc
