=== Docker Run Log for 771052 ===
Started at: Mi 29. Okt 17:16:52 CET 2025

[2025-10-29 17:17:00] START: Running container for 771052
[2025-10-29 17:17:00] SUCCESS: Container 5c62e9e729a98c2272fa0f0ca9950fdc3871c7a0b6ac4f46ab4ef8afde0458e5 started for 771052
=== Container logs for 771052 ===
Traceback (most recent call last):
  File "/snippet.py", line 3, in <module>
    from django.contrib.auth.models import User
  File "/usr/local/lib/python3.11/site-packages/django/contrib/auth/models.py", line 5, in <module>
    from django.contrib.auth.base_user import AbstractBaseUser, BaseUserManager
  File "/usr/local/lib/python3.11/site-packages/django/contrib/auth/base_user.py", line 43, in <module>
    class AbstractBaseUser(models.Model):
  File "/usr/local/lib/python3.11/site-packages/django/db/models/base.py", line 131, in __new__
    app_config = apps.get_containing_app_config(module)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/apps/registry.py", line 260, in get_containing_app_config
    self.check_apps_ready()
  File "/usr/local/lib/python3.11/site-packages/django/apps/registry.py", line 137, in check_apps_ready
    settings.INSTALLED_APPS
  File "/usr/local/lib/python3.11/site-packages/django/conf/__init__.py", line 81, in __getattr__
    self._setup(name)
  File "/usr/local/lib/python3.11/site-packages/django/conf/__init__.py", line 61, in _setup
    raise ImproperlyConfigured(
django.core.exceptions.ImproperlyConfigured: Requested setting INSTALLED_APPS, but settings are not configured. You must either define the environment variable DJANGO_SETTINGS_MODULE or call settings.configure() before accessing settings.
=== End of logs for 771052 ===
[2025-10-29 17:17:03] INFO: Container 5c62e9e729a98c2272fa0f0ca9950fdc3871c7a0b6ac4f46ab4ef8afde0458e5 has stopped
