=== Docker Run Log for 61dc4abed6186117f2a70b058a2b8d14 ===
Started at: Mi 29. Okt 16:25:02 CET 2025

[2025-10-29 16:25:11] START: Running container for 61dc4abed6186117f2a70b058a2b8d14
[2025-10-29 16:25:11] SUCCESS: Container a12abe679020dd3e71975a7d953ad1707f70864950d54591be2fbc77cb296652 started for 61dc4abed6186117f2a70b058a2b8d14
=== Container logs for 61dc4abed6186117f2a70b058a2b8d14 ===
Traceback (most recent call last):
  File "/snippet.py", line 2, in <module>
    from django.contrib.auth.models import AbstractBaseUser
  File "/usr/local/lib/python3.11/site-packages/django/contrib/auth/models.py", line 5, in <module>
    from django.contrib.auth.base_user import AbstractBaseUser, BaseUserManager
  File "/usr/local/lib/python3.11/site-packages/django/contrib/auth/base_user.py", line 43, in <module>
    class AbstractBaseUser(models.Model):
  File "/usr/local/lib/python3.11/site-packages/django/db/models/base.py", line 131, in __new__
    app_config = apps.get_containing_app_config(module)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/apps/registry.py", line 260, in get_containing_app_config
    self.check_apps_ready()
  File "/usr/local/lib/python3.11/site-packages/django/apps/registry.py", line 137, in check_apps_ready
    settings.INSTALLED_APPS
  File "/usr/local/lib/python3.11/site-packages/django/conf/__init__.py", line 81, in __getattr__
    self._setup(name)
  File "/usr/local/lib/python3.11/site-packages/django/conf/__init__.py", line 61, in _setup
    raise ImproperlyConfigured(
django.core.exceptions.ImproperlyConfigured: Requested setting INSTALLED_APPS, but settings are not configured. You must either define the environment variable DJANGO_SETTINGS_MODULE or call settings.configure() before accessing settings.
=== End of logs for 61dc4abed6186117f2a70b058a2b8d14 ===
[2025-10-29 16:25:13] INFO: Container a12abe679020dd3e71975a7d953ad1707f70864950d54591be2fbc77cb296652 has stopped
