=== Docker Run Log for 1228626 ===
Started at: Mi 29. Okt 11:59:40 CET 2025

[2025-10-29 11:59:47] START: Running container for 1228626
[2025-10-29 11:59:47] SUCCESS: Container 2956373a450ddb73b7c0dbc3d1a29a7463ab96eb4c27609557611621deab6fdf started for 1228626
=== Container logs for 1228626 ===
Traceback (most recent call last):
  File "/snippet.py", line 2, in <module>
    from django.contrib.gis.geos import Point
  File "/usr/local/lib/python3.11/site-packages/django/contrib/gis/geos/__init__.py", line 6, in <module>
    from .collections import (  # NOQA
  File "/usr/local/lib/python3.11/site-packages/django/contrib/gis/geos/collections.py", line 7, in <module>
    from django.contrib.gis.geos.geometry import GEOSGeometry, LinearGeometryMixin
  File "/usr/local/lib/python3.11/site-packages/django/contrib/gis/geos/geometry.py", line 9, in <module>
    from django.contrib.gis import gdal
  File "/usr/local/lib/python3.11/site-packages/django/contrib/gis/gdal/__init__.py", line 29, in <module>
    from django.contrib.gis.gdal.datasource import DataSource
  File "/usr/local/lib/python3.11/site-packages/django/contrib/gis/gdal/datasource.py", line 40, in <module>
    from django.contrib.gis.gdal.driver import Driver
  File "/usr/local/lib/python3.11/site-packages/django/contrib/gis/gdal/driver.py", line 5, in <module>
    from django.contrib.gis.gdal.prototypes import ds as capi
  File "/usr/local/lib/python3.11/site-packages/django/contrib/gis/gdal/prototypes/ds.py", line 10, in <module>
    from django.contrib.gis.gdal.libgdal import lgdal
  File "/usr/local/lib/python3.11/site-packages/django/contrib/gis/gdal/libgdal.py", line 64, in <module>
    raise ImproperlyConfigured(
django.core.exceptions.ImproperlyConfigured: Could not find the GDAL library (tried "gdal", "GDAL", "gdal3.10.0", "gdal3.9.0", "gdal3.8.0", "gdal3.7.0", "gdal3.6.0", "gdal3.5.0", "gdal3.4.0", "gdal3.3.0", "gdal3.2.0", "gdal3.1.0"). Is GDAL installed? If it is, try setting GDAL_LIBRARY_PATH in your settings.
=== End of logs for 1228626 ===
[2025-10-29 11:59:49] INFO: Container 2956373a450ddb73b7c0dbc3d1a29a7463ab96eb4c27609557611621deab6fdf has stopped
